# Generated by Django 3.0.7 on 2020-10-12 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0004_reserva_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='mesas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entregar.Mesas'),
        ),
    ]
