# Generated by Django 3.0.7 on 2020-10-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0005_auto_20201011_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='user',
        ),
        migrations.AlterField(
            model_name='mesas',
            name='numero',
            field=models.IntegerField(max_length=15),
        ),
    ]
