# Generated by Django 3.0.7 on 2020-10-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0006_auto_20201012_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesas',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
