# Generated by Django 3.0.7 on 2020-10-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0010_auto_20201015_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
