# Generated by Django 3.0.7 on 2020-10-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0011_delete_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
