# Generated by Django 3.0.7 on 2020-10-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0012_delete_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservar',
        ),
    ]
