# Generated by Django 3.0.7 on 2020-10-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0014_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('EMPRESARIAL', 'EMPRESARIAL'), ('SOCIAL', 'SOCIAL'), ('CASAL', 'CASAL'), ('VIP', 'VIP')], max_length=15),
        ),
    ]
