# Generated by Django 3.0.7 on 2020-10-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0015_auto_20201015_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='beds',
            new_name='cadeiras',
        ),
    ]
