# Generated by Django 3.0.7 on 2020-10-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0016_auto_20201016_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tipo_de_pedido',
            field=models.CharField(choices=[('RECEBER ENCASA', 'RECEBER ENCASA'), ('COMENDO NO RESTAURANTE', 'COMENDO NO RESTAURANTE'), ('LEVANTAR PESSOALMENTE', 'LEVANTAR PESSOALMENTE')], max_length=200, null=True),
        ),
    ]
