# Generated by Django 3.0.7 on 2020-10-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0017_order_tipo_de_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tipo_de_pedido',
            field=models.CharField(choices=[('RECEBER ENCASA', 'RECEBER ENCASA'), ('COMER NO RESTAURANTE', 'COMER NO RESTAURANTE'), ('LEVANTAR PESSOALMENTE', 'LEVANTAR PESSOALMENTE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='SemFT.png', null=True, upload_to=''),
        ),
    ]
