# Generated by Django 3.0.7 on 2020-10-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0018_auto_20201019_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Prato_2', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Promocao do Dia', 'Promocao do Dia'), ('Preco Normal', 'Preco Normal')], max_length=200),
        ),
    ]
