# Generated by Django 3.0.7 on 2020-10-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0020_lotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotacao',
            name='numero_de_clientes',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
