# Generated by Django 3.0.7 on 2020-10-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0021_auto_20201020_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotacao',
            name='capacidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='numero_de_clientes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
