# Generated by Django 3.0.7 on 2020-10-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0022_auto_20201020_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotacao',
            name='capacidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='numero_de_clientes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
