# Generated by Django 3.0.7 on 2020-10-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0023_auto_20201022_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas_Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
