# Generated by Django 3.0.7 on 2020-10-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0025_auto_20201022_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('MasterCard', 'MasterCard')], max_length=200, null=True),
        ),
    ]
