# Generated by Django 3.0.7 on 2020-10-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0026_auto_20201022_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='preco_a_pagar',
            field=models.IntegerField(null=True),
        ),
    ]
