# Generated by Django 3.0.7 on 2020-10-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0027_auto_20201022_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('contacto', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
